# Generated by Django 4.0.3 on 2022-03-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_shift_shift_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shifttime',
            name='afternoon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shifttime',
            name='evening',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shifttime',
            name='morning',
            field=models.BooleanField(default=False),
        ),
    ]
