# Generated by Django 4.0.3 on 2022-03-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_shift_shift_set_alter_shifttime_afternoon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='date',
        ),
        migrations.AddField(
            model_name='worker',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
